In [18]:
import pandas as pd
import numpy as np


In [15]:
matrix1 = pd.read_csv('matrix_test1.csv', header = None, sep=';')
matrix1 = matrix1.dropna(axis=1)
matrix1.as_matrix()

array([[-9.26173 , -8.71059 ,  6.18502 , -9.83969 ],
       [ 2.44966 , -4.27093 , -8.09702 ,  3.05287 ],
       [ 4.48866 , -2.61649 ,  8.4769  , -9.73078 ],
       [-0.126563,  5.38567 ,  4.38391 ,  8.3415  ]])

In [16]:
matrix2 = pd.read_csv('matrix_test2.csv', header = None, sep=';')
matrix2 = matrix2.dropna(axis=1)
matrix2.as_matrix()

array([[-7.66101  ,  6.12999  , -5.59276  ,  9.48332  ],
       [-1.4372   ,  9.05001  , -6.2979   ,  0.845171 ],
       [-7.10052  , -7.37378  , -0.839738 ,  0.0762239],
       [-5.85758  , -1.36195  , -6.01223  , -3.85811  ]])

In [19]:
np.matmul(matrix1.as_matrix(), matrix2.as_matrix())

array([[  97.19297924, -167.81104987,  160.62174092,  -56.75983467],
       [  26.98193304,   31.91221993,    1.64234837,    7.22574877],
       [ -33.81882539,  -45.41777961,   42.75970666,   78.54457969],
       [ -86.75972872,    4.27784363,  -87.04292697,  -28.49669118]])